version: "3.8"

services:
  inhouse_bot:
    image: mrtolkien/inhouse_bot
    build:
      context: .
      target: inhouse_bot_dev
    env_file:
    - .env

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: inhouse_bot

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    pgdata:
