version: "3.8"

services:
  inhouse_bot:
    image: mrtolkien/inhouse_bot
    build:
      context: .
      target: inhouse_bot_dev
    env_file:
    - .env

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pwd
