version: "3.8"

services:
  inhouse_bot:
    image: mrtolkien/inhouse_bot
    container_name: inhouse_bot
    restart: always
    build:
      context: .
    volumes:
    - type: bind
      source: ./data
      target: /data
    env_file:
      - .env
